modLoader="javafml"
loaderVersion="[43,)" 
license="MIT"

[[mods]] #mandatory
modId="expansioncraft"
version="0.0.1-1.19.2" 
displayName="Expansion Craft" 

#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 

logoFile="examplemod.png"
credits="Programing: MarcelineBadBoy, J4cob2; Art: K0giusz"
authors="MarcelineBadBoy, K0giusz, J4cob2"
description='''
'''

[[dependencies.examplemod]]
    modId="forge" 
    mandatory=true 
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"